##服务配置
server:
  port: 8080

##数据库配置
spring: 
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: admin

##日志配置
logging:
  level:
    org:
      springframework: info